In [2]:
import numpy as np

In [3]:
x = np.array([1.0 , 2.0, 3.0])

In [5]:
type(x)

numpy.ndarray

In [10]:
y = np.array([2.0, 4.0, 6.0])
x + y

array([3., 6., 9.])

In [7]:
x - y

array([-1., -2., -3.])

In [8]:
x * y

array([ 2.,  8., 18.])

In [9]:
x / y

array([0.5, 0.5, 0.5])

In [12]:
x / 2.0

array([0.5, 1. , 1.5])

In [13]:
A = np.array([[1, 2], [3, 4]])

In [14]:
print(A)

[[1 2]
 [3 4]]


In [15]:
A.shape

(2, 2)

In [17]:
A.dtype

dtype('int32')

In [18]:
B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [19]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [22]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

In [23]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [24]:
X[0]

array([51, 55])

In [25]:
X[0][1]

55

In [28]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [33]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [38]:
X[[1, 2, 3]]

array([55, 14, 19])

In [31]:
X > 15
X[X>15]

array([51, 55, 19])